# Site settings
title: Pankil Shah
email: pankils@gmail.com
description: >-
  Sr. Technical Program Manager specializing in AI-Native Platform Engineering & Governance.
baseurl: ""
url: "https://pankilshahattpm.github.io"

# Social profiles
github_username: pankilshahattpm
linkedin_username: pankilshah

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Render settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
